In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
db = pd.read_csv('pima-indians-diabetes.csv', sep=";")

In [3]:
print(db.shape)

(768, 9)


In [4]:
print(db.columns)

Index(['grossesses', 'glucose', 'press_art', 'peau', 'insuline', 'IMC',
       'fctDiabete', 'age', 'resultat'],
      dtype='object')


In [5]:
print(db.dtypes)

grossesses      int64
glucose         int64
press_art       int64
peau            int64
insuline        int64
IMC           float64
fctDiabete    float64
age             int64
resultat       object
dtype: object


In [6]:
print('Count of Features per Data Type:')
db.dtypes.value_counts()

Count of Features per Data Type:


int64      6
float64    2
object     1
dtype: int64

In [7]:
print('Number of Duplicates:', len(db[db.duplicated()]))

Number of Duplicates: 0


In [8]:
print('Number of Missing Values:', db.isnull().sum().sum())

Number of Missing Values: 0


In [9]:
db.describe()

grossesses     glucose   press_art        peau    insuline         IMC  \
count  768.000000  768.000000  768.000000  768.000000  768.000000  768.000000   
mean     3.845052  120.894531   69.105469   20.536458   79.799479   31.992578   
std      3.369578   31.972618   19.355807   15.952218  115.244002    7.884160   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      1.000000   99.000000   62.000000    0.000000    0.000000   27.300000   
50%      3.000000  117.000000   72.000000   23.000000   30.500000   32.000000   
75%      6.000000  140.250000   80.000000   32.000000  127.250000   36.600000   
max     17.000000  199.000000  122.000000   99.000000  846.000000   67.100000   

       fctDiabete         age  
count  768.000000  768.000000  
mean     0.471876   33.240885  
std      0.331329   11.760232  
min      0.078000   21.000000  
25%      0.243750   24.000000  
50%      0.372500   29.000000  
75%      0.626250   41.000000  
max      2.420000   81.000000

In [10]:
db.head()

grossesses  glucose  press_art  peau  insuline   IMC  fctDiabete  age  \
0           6      148         72    35         0  33.6       0.627   50   
1           1       85         66    29         0  26.6       0.351   31   
2           8      183         64     0         0  23.3       0.672   32   
3           1       89         66    23        94  28.1       0.167   21   
4           0      137         40    35       168  43.1       2.288   33   

     resultat  
0      Malade  
1  Non-malade  
2      Malade  
3  Non-malade  
4      Malade

In [38]:
data = db.values # on fait la matrice
x = data[: , :-1] # tout le reste
y = data[:, -1] # malade ou non malade

In [12]:
print(x[:10,:])

[[6 148 72 35 0 33.6 0.627 50]
 [1 85 66 29 0 26.6 0.351 31]
 [8 183 64 0 0 23.3 0.672 32]
 [1 89 66 23 94 28.1 0.167 21]
 [0 137 40 35 168 43.1 2.288 33]
 [5 116 74 0 0 25.6 0.201 30]
 [3 78 50 32 88 31.0 0.248 26]
 [10 115 0 0 0 35.3 0.134 29]
 [2 197 70 45 543 30.5 0.158 53]
 [8 125 96 0 0 0.0 0.232 54]]


In [13]:
print(y)

['Malade' 'Non-malade' 'Malade' 'Non-malade' 'Malade' 'Non-malade'
 'Malade' 'Non-malade' 'Malade' 'Malade' 'Non-malade' 'Malade'
 'Non-malade' 'Malade' 'Malade' 'Malade' 'Malade' 'Malade' 'Non-malade'
 'Malade' 'Non-malade' 'Non-malade' 'Malade' 'Malade' 'Malade' 'Malade'
 'Malade' 'Non-malade' 'Non-malade' 'Non-malade' 'Non-malade' 'Malade'
 'Non-malade' 'Non-malade' 'Non-malade' 'Non-malade' 'Non-malade' 'Malade'
 'Malade' 'Malade' 'Non-malade' 'Non-malade' 'Non-malade' 'Malade'
 'Non-malade' 'Malade' 'Non-malade' 'Non-malade' 'Malade' 'Non-malade'
 'Non-malade' 'Non-malade' 'Non-malade' 'Malade' 'Non-malade' 'Non-malade'
 'Malade' 'Non-malade' 'Non-malade' 'Non-malade' 'Non-malade' 'Malade'
 'Non-malade' 'Non-malade' 'Malade' 'Non-malade' 'Malade' 'Non-malade'
 'Non-malade' 'Non-malade' 'Malade' 'Non-malade' 'Malade' 'Non-malade'
 'Non-malade' 'Non-malade' 'Non-malade' 'Non-malade' 'Malade' 'Non-malade'
 'Non-malade' 'Non-malade' 'Non-malade' 'Non-malade' 'Malade' 'Non-malade'
 'No

In [14]:
from sklearn.impute import SimpleImputer

In [15]:
imputer = SimpleImputer(missing_values=0, strategy='mean') 

In [16]:
imputer.fit(x[:, 1:]) 

SimpleImputer(missing_values=0)

In [17]:
x[:, 1:] = imputer.transform(x[:, 1:])

In [18]:
print(x[0:10,:])

[[6 148.0 72.0 35.0 155.5482233502538 33.6 0.627 50.0]
 [1 85.0 66.0 29.0 155.5482233502538 26.6 0.351 31.0]
 [8 183.0 64.0 29.153419593345657 155.5482233502538 23.3 0.672 32.0]
 [1 89.0 66.0 23.0 94.0 28.1 0.167 21.0]
 [0 137.0 40.0 35.0 168.0 43.1 2.288 33.0]
 [5 116.0 74.0 29.153419593345657 155.5482233502538 25.6 0.201 30.0]
 [3 78.0 50.0 32.0 88.0 31.0 0.248 26.0]
 [10 115.0 72.40518417462484 29.153419593345657 155.5482233502538 35.3
  0.134 29.0]
 [2 197.0 70.0 45.0 543.0 30.5 0.158 53.0]
 [8 125.0 96.0 29.153419593345657 155.5482233502538 32.457463672391015
  0.232 54.0]]


In [19]:
# from sklearn.compose import ColumnTransformer
# from sklearn.preprocessing import OneHotEncoder
# diab = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
# x = np.array(diab.fit_transform(x))

In [20]:
# print("OneHotEncoder")

In [21]:
print(x)

[[6 148.0 72.0 ... 33.6 0.627 50.0]
 [1 85.0 66.0 ... 26.6 0.351 31.0]
 [8 183.0 64.0 ... 23.3 0.672 32.0]
 ...
 [5 121.0 72.0 ... 26.2 0.245 30.0]
 [1 126.0 60.0 ... 30.1 0.349 47.0]
 [1 93.0 70.0 ... 30.4 0.315 23.0]]


In [22]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [23]:
print(y)

[0 1 0 1 0 1 0 1 0 0 1 0 1 0 0 0 0 0 1 0 1 1 0 0 0 0 0 1 1 1 1 0 1 1 1 1 1
 0 0 0 1 1 1 0 1 0 1 1 0 1 1 1 1 0 1 1 0 1 1 1 1 0 1 1 0 1 0 1 1 1 0 1 0 1
 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1 1 1 0 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 0 0
 0 1 1 0 0 0 1 1 1 0 1 1 1 0 0 1 1 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1
 1 1 1 1 0 1 0 0 1 1 1 0 1 1 1 1 0 0 1 1 1 1 0 0 1 1 1 0 1 0 1 0 1 1 1 1 1
 0 0 0 0 0 1 1 0 0 1 0 1 0 0 0 1 1 1 1 1 1 0 0 1 0 1 1 1 0 0 0 0 1 0 0 0 0
 1 1 1 1 1 0 1 1 0 0 1 1 1 0 0 0 0 1 1 1 0 0 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1
 0 1 0 1 1 0 1 0 1 1 0 0 1 1 1 1 1 0 1 1 1 0 1 1 0 0 1 1 0 1 1 1 0 0 0 1 1
 0 1 0 1 0 0 1 0 1 1 0 1 0 0 1 1 0 1 0 1 1 0 1 0 1 0 0 0 1 1 0 1 0 1 1 1 0
 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 0 0 1 0 0 1 1 0 1 1 0 1 1 0
 0 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 0 0 0 1 1 0 1 1 0 1 1 0 1 0 0 1 0 1 0 1 0
 1 0 0 1 1 1 1 0 0 1 0 1 0 1 1 1 1 0 0 1 0 1 0 1 1 1 1 1 0 1 1 1 1 0 1 1 0
 0 0 1 1 0 1 1 0 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 0
 1 1 1 0 0 1 1 1 1 1 1 1 

In [24]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state = 1)

In [25]:
print(x_train)

[[9 145.0 80.0 ... 37.9 0.637 40.0]
 [10 129.0 62.0 ... 41.2 0.441 38.0]
 [7 102.0 74.0 ... 37.2 0.204 45.0]
 ...
 [13 126.0 90.0 ... 43.4 0.583 42.0]
 [4 171.0 72.0 ... 43.6 0.479 26.0]
 [9 102.0 76.0 ... 32.9 0.665 46.0]]


In [26]:
print(x_test)

[[7 136.0 74.0 ... 26.0 0.647 51.0]
 [1 151.0 60.0 ... 26.1 0.179 22.0]
 [6 109.0 60.0 ... 25.0 0.206 27.0]
 ...
 [8 188.0 78.0 ... 47.9 0.137 43.0]
 [5 136.0 82.0 ... 32.457463672391015 0.64 69.0]
 [4 90.0 72.40518417462484 ... 28.0 0.61 31.0]]


In [27]:
print(y_train)

[0 0 1 1 1 1 0 0 1 1 0 1 0 0 1 1 0 0 1 1 0 1 0 1 1 1 0 1 1 0 1 1 1 1 0 1 1
 1 1 1 0 1 1 1 0 0 0 1 1 1 0 0 1 1 1 0 1 1 0 0 1 0 0 1 1 0 1 1 1 0 0 1 1 1
 1 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 1 1 1 0 1 0 1 1 1 1 0 0 1 1 1 1 0
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 0 0 0 1 1 0 0 1 0 0 1 1 0 1 0 1 0
 1 1 1 0 0 1 0 1 1 0 0 0 1 1 0 1 0 0 1 0 0 1 1 0 0 0 1 0 1 1 0 1 0 1 1 1 1
 1 0 0 0 1 1 1 1 0 0 1 1 1 1 1 0 0 1 1 1 1 0 1 1 1 1 1 0 1 1 1 1 0 1 1 1 0
 0 1 0 1 1 1 0 1 1 1 0 0 1 1 0 1 1 1 1 1 1 1 1 0 1 0 1 0 1 0 1 1 1 1 1 1 0
 1 0 0 1 0 0 0 1 0 1 1 0 0 1 0 0 0 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0
 1 1 1 1 1 0 1 0 1 1 1 1 1 1 1 1 1 0 1 0 1 1 0 0 1 1 1 1 1 1 1 0 1 1 0 1 1
 1 1 0 0 1 1 1 1 1 1 0 1 0 0 1 1 0 1 1 1 1 1 0 1 1 1 1 1 0 0 1 1 0 0 1 1 0
 1 1 1 1 1 1 0 1 1 1 0 0 1 0 0 0 1 1 1 1 0 1 0 1 1 1 1 0 1 1 1 0 1 0 1 0 0
 1 0 1 1 1 1 1 1 0 1 1 0 1 1 0 1 1 1 1 0 1 1 1 0 1 0 1 1 1 1 1 0 0 0 1 1 1
 1 0 0 0 0 0 0 0 1 1 1 0 1 1 1 1 0 1 0 1 1 0 1 1 0 1 1 1 1 1 0 1 0 1 0 1 0
 1 1 1 0 1 0 0 1 1 0 0 1 

In [28]:
print(y_test)

[1 1 1 1 1 1 1 1 1 1 1 1 0 0 1 0 0 1 1 1 0 0 0 0 1 1 1 0 1 0 0 1 1 0 1 0 1
 1 1 1 1 1 1 0 1 1 0 0 1 0 1 1 0 1 0 1 0 1 1 1 1 1 0 1 0 1 0 0 1 0 0 1 1 1
 0 0 0 1 1 0 0 1 0 0 1 1 0 1 1 1 1 1 1 1 0 1 1 1 0 1 1 1 0 1 1 1 0 1 0 1 0
 1 1 1 0 1 1 0 1 0 1 0 0 1 1 1 1 0 1 1 0 1 0 1 1 1 1 1 0 1 0 1 1 0 0 0 1 1
 0 1 1 0 1 1]


In [29]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [30]:
x_train.shape

(614, 8)

In [31]:
print(x_train)

[[ 1.51659096  0.75964146  0.62216681 ...  0.83602667  0.52952571
   0.56793202]
 [ 1.81201827  0.23457642 -0.82873535 ...  1.32024996 -0.06968859
   0.39844951]
 [ 0.92573636 -0.65147082  0.13853276 ...  0.73331264 -0.79424873
   0.99163829]
 ...
 [ 2.69830017  0.13612673  1.42822356 ...  1.64306548  0.36443605
   0.73741453]
 [ 0.03945446  1.61287214 -0.0226786  ...  1.67241235  0.04648561
  -0.61844554]
 [ 1.51659096 -0.65147082  0.29974411 ...  0.10235502  0.61512775
   1.07637954]]


In [32]:
print(x_test)

[[ 0.92573636  0.46429238  0.13853276 ... -0.91011185  0.56009786
   1.50008581]
 [-0.84682744  0.95654085 -0.9899467  ... -0.89543842 -0.87067912
  -0.95741055]
 [ 0.63030906 -0.42175487 -0.9899467  ... -1.05684618 -0.78813429
  -0.53370428]
 ...
 [ 1.22116366  2.17075374  0.46095546 ...  2.30336997 -0.99908218
   0.82215578]
 [ 0.33488176  0.46429238  0.78337816 ...  0.03741975  0.53869735
   3.02542839]
 [ 0.03945446 -1.0452696   0.00998155 ... -0.61664319  0.44698088
  -0.19473927]]


In [33]:
from sklearn.linear_model import LogisticRegression

In [34]:
lr = LogisticRegression(random_state=0)
lr.fit(x_train, y_train)

LogisticRegression(random_state=0)

In [35]:
aux = sc.transform([[6,148,72,35,0,33.6,0.627,50]])

print(lr.predict(aux))
# print(sc.mean_)

[0]


In [36]:
y_pred = lr.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [0 1]
 [1 1]
 [0 1]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [1 0]
 [1 0]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [1 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 1]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]

In [37]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[31 24]
 [11 88]]


0.7727272727272727

In [40]:
# lr.score(x_train, y_train)

0.7719869706840391